### PR TITLE
Add support for on/off comments

### LINKED ISSUE #193: Add possibilities to skip blocks and lines?
Background:

When we implemented blacken-docs in Read the Docs, we had a couple of cases where we would have liked to skip linting of the code example. But we also didn't want to put `# noqa` in the code-examples themselves, since that means copy-pasting the code would also require additional clean-up. Our cases were - however - easy to ignore and move on from. So we did.

Now, I see [a Django proposal](https://github.com/django/django/pull/16261) to use blacken-docs is generating mostly great changes, but there are also a few issues getting the PR merged.

Solution?

I'm not sure what would be a good way forwards. But I get the idea that being able to specify what to skip might work well.

Please have a look here: https://github.com/django/django/pull/16261

Thanks for the great project :heart:

### PR DESCRIPTION
**Pull request by pawamoy**
Closes #193

### CODE REVIEW

**Comment by pawamoy** [comment]
Not sure yet if/how you'd like to add support for rST and Latex.

**Comment by pawamoy** [comment]
OK we now have a single regex for the three languages, and tests for each.

**Comment by pawamoy** [comment]
Pre-commit doesn't use the modified code, therefore my examples in the README got formatted :sweat_smile: 
I suppose we should first release, then modify back to remove spaces in `f(1, 2, 3)`, and this time it won't get formatted.

**Comment by pawamoy** [comment]
Also note sure how to cover line 120.

**Comment by pawamoy** [comment]
@adamchainz is it OK if I ping you from time to time? That's what I ask from others when I don't answer, but you might work differently, and I don't want to bother you :slightly_smiling_face:

**Comment by adamchainz** [comment]
Please don’t ping

**Comment by pawamoy** [comment]
I stopped using blacken-docs some time ago, so I'll close this PR, but feel free to reopen it if you or other users are still interested in getting it merged :slightly_smiling_face:

**Comment by adamchainz** [comment]
I still intend to add this

**Comment by adamchainz** [comment]
Thank you for the PR, I finally found time to review and finish it off. You may be interested in reading the intermediate commits.

**Comment by pawamoy** [comment]
Awesome, thanks. You made some clever optimizations and simplifications that I will keep in mind!

**Pull request merged**
